// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwzgsiysdwsmmkgqmbsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3emdzaXlzZHdzbW1rZ3FtYnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mzk4OTcsImV4cCI6MjA2NTQxNTg5N30.6tRtMBswe8MCfNLFRGDxioVmTjBTxhx79c_KXlV16x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);